package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.jdbc.PessoaDaoJDBC;
import br.edu.ifsp.pep.modelo.Pessoa;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class PessoaListForm extends javax.swing.JFrame {

    /**
     * Creates new form PessoaListForm
     */
    private PessoaDaoJDBC pessoaDaoJDBC = new PessoaDaoJDBC();
    private List<Pessoa> pessoas = pessoaDaoJDBC.getTodos();
    
    public PessoaListForm() {
        initComponents();
        atualizarTabela();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAtributos = new javax.swing.JTable();
        FrameBarraPesquisa = new javax.swing.JPanel();
        nomeBarra = new javax.swing.JLabel();
        BExcluir = new javax.swing.JButton();
        JPesquisar = new javax.swing.JTextField();
        BPesquisar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaAtributos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Email", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(TabelaAtributos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        nomeBarra.setText("Nome");

        BExcluir.setText("Excluir");
        BExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExcluirActionPerformed(evt);
            }
        });

        JPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPesquisarActionPerformed(evt);
            }
        });

        BPesquisar1.setText("Pesquisar");
        BPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameBarraPesquisaLayout = new javax.swing.GroupLayout(FrameBarraPesquisa);
        FrameBarraPesquisa.setLayout(FrameBarraPesquisaLayout);
        FrameBarraPesquisaLayout.setHorizontalGroup(
            FrameBarraPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBarraPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPesquisar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BExcluir)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        FrameBarraPesquisaLayout.setVerticalGroup(
            FrameBarraPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameBarraPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameBarraPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeBarra)
                    .addComponent(BExcluir)
                    .addComponent(JPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BPesquisar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(FrameBarraPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(FrameBarraPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPesquisarActionPerformed

    private void BExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExcluirActionPerformed
        int linha = TabelaAtributos.getSelectedRow();
        if (linha != -1) {

            try {
                pessoaDaoJDBC.remover(pessoas.get(linha).getCodigo());
                JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso");
            } catch (Exception ex) {
                Logger.getLogger(PessoaListForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        pessoas = pessoaDaoJDBC.getTodos();
        atualizarTabela();
    }//GEN-LAST:event_BExcluirActionPerformed

    private void BPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPesquisar1ActionPerformed
        // TODO add your handling code here:
        
        if ("".equals(JPesquisar.getText()))
            pessoas = pessoaDaoJDBC.getTodos();
        else
            pessoas = pessoaDaoJDBC.consultarPeloNome(JPesquisar.getText());
        
        atualizarTabela();
        
    }//GEN-LAST:event_BPesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaListForm().setVisible(true);
            }
        });
    }
    
    private void atualizarTabela() {

        DefaultTableModel modelo = (DefaultTableModel) TabelaAtributos.getModel();
        //Remove as linhas da tabela
        modelo.setNumRows(0);
        for (Pessoa pessoa : pessoas) {
            modelo.addRow(new Object[]{
                pessoa.getCodigo(), pessoa.getNome(), 
                pessoa.getEmail(), pessoa.getTelefone()
            });
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExcluir;
    private javax.swing.JButton BPesquisar1;
    private javax.swing.JPanel FrameBarraPesquisa;
    private javax.swing.JTextField JPesquisar;
    private javax.swing.JTable TabelaAtributos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeBarra;
    // End of variables declaration//GEN-END:variables
}
