package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.DAO;
import br.edu.ifsp.pep.jdbc.PessoaDaoJDBC;
import br.edu.ifsp.pep.modelo.Pessoa;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class PessoaListForm extends javax.swing.JDialog {

    private DAO pessoaDao = new PessoaDaoJDBC();
    private List<Pessoa> pessoas;
    
    private Pessoa pessoaSelecionada = null;

    /**
     * Creates new form PessoaListForm
     */
    public PessoaListForm(Frame parent, boolean modal) { // faz parte da extend JDialog
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfNomePesquisa = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();
        bRetornar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "E-mail", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel1.setText("Nome");

        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        bRetornar.setText("Retornar");
        bRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetornarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bRetornar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar)
                    .addComponent(bExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRetornar)
                    .addComponent(bCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed

        atualizarTabela();
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetornarActionPerformed

        int linha = tabela.getSelectedRow();

        if (linha > -1) {
            pessoaSelecionada = pessoas.get(linha);
           
            //Fecha esta tela (janela)
            this.dispose();
            
        } else {
            System.out.println("Selecione uma Pessoa.");
        }


    }//GEN-LAST:event_bRetornarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        // TODO add your handling code here:
        int linha = tabela.getSelectedRow();
        if (linha != -1) {

            try {
                pessoaDao.remover(pessoas.get(linha).getCodigo());
                JOptionPane.showMessageDialog(rootPane, "Deletado com sucesso");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        
        pessoas = pessoaDao.getTodos();
        atualizarTabela();
    }//GEN-LAST:event_bExcluirActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JButton bRetornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tfNomePesquisa;
    // End of variables declaration//GEN-END:variables

   
    public Pessoa getPessoaSelecionada() {
        return pessoaSelecionada;
    }
   
    private void atualizarTabela() {

        pessoas = pessoaDao.consultarPeloNome(tfNomePesquisa.getText());

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

        //Remove as linhas da tabela
        modelo.setNumRows(0);

        for (Pessoa pessoa : pessoas) {
            modelo.addRow(new Object[]{
                pessoa.getCodigo(), pessoa.getNome(),
                pessoa.getEmail(), pessoa.getTelefone()
            });
        }

    }
}
