package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.DAO;
import br.edu.ifsp.pep.jdbc.PessoaDaoJDBC;
import br.edu.ifsp.pep.modelo.Pessoa;
import java.awt.Component;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class PessoaForm extends javax.swing.JFrame {

    //Armazena em memória (List)
//    private PessoaDao pessoaDao = new PessoaDao();
    //Armazena em Banco de Dados
    private DAO pessoaDao = new PessoaDaoJDBC();

    /**
     * Creates new form PessoaForm
     */
    public PessoaForm() {
        initComponents();
        controlarVisibilidadeBotoes(true);
        controlarVisibilidadeComponentes(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pComponentes = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lDataNascimento = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lSalario = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        dcDataNascimento = new com.toedter.calendar.JDateChooser();
        tfEndereco = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        tfEmail = new javax.swing.JTextField();
        tfSalario = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        bCadastrar = new javax.swing.JButton();
        bAlterar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bGravar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pComponentes.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(51, 102, 255));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Cadastro de Pessoa");

        lNome.setText("Nome");

        lDataNascimento.setText("Data Nascimento");

        lEndereco.setText("Endereço");

        lTelefone.setText("Telefone");

        lEmail.setText("E-mail");

        lSalario.setText("Salário");

        dcDataNascimento.setDateFormatString("dd/MM/yyyy");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tfSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bCadastrar.setBackground(new java.awt.Color(51, 153, 255));
        bCadastrar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        bCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        bCadastrar.setText("Cadastrar");
        bCadastrar.setBorderPainted(false);
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bAlterar.setBackground(new java.awt.Color(51, 153, 255));
        bAlterar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        bAlterar.setForeground(new java.awt.Color(255, 255, 255));
        bAlterar.setText("Alterar");
        bAlterar.setBorderPainted(false);
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });

        bExcluir.setBackground(new java.awt.Color(51, 153, 255));
        bExcluir.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        bExcluir.setForeground(new java.awt.Color(255, 255, 255));
        bExcluir.setText("Excluir");
        bExcluir.setBorderPainted(false);
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bGravar.setBackground(new java.awt.Color(51, 153, 255));
        bGravar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        bGravar.setForeground(new java.awt.Color(255, 255, 255));
        bGravar.setText("Gravar");
        bGravar.setBorderPainted(false);
        bGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGravarActionPerformed(evt);
            }
        });

        bCancelar.setBackground(new java.awt.Color(51, 153, 255));
        bCancelar.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        bCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bCancelar.setText("Cancelar");
        bCancelar.setBorderPainted(false);
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pComponentesLayout = new javax.swing.GroupLayout(pComponentes);
        pComponentes.setLayout(pComponentesLayout);
        pComponentesLayout.setHorizontalGroup(
            pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pComponentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pComponentesLayout.createSequentialGroup()
                        .addComponent(lEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEndereco))
                    .addGroup(pComponentesLayout.createSequentialGroup()
                        .addComponent(lEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEmail))
                    .addGroup(pComponentesLayout.createSequentialGroup()
                        .addComponent(lNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome))
                    .addGroup(pComponentesLayout.createSequentialGroup()
                        .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pComponentesLayout.createSequentialGroup()
                                .addComponent(lTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pComponentesLayout.createSequentialGroup()
                                .addComponent(lSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pComponentesLayout.createSequentialGroup()
                                .addComponent(lDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pComponentesLayout.setVerticalGroup(
            pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pComponentesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pComponentesLayout.createSequentialGroup()
                        .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pComponentesLayout.createSequentialGroup()
                                .addComponent(lTitulo)
                                .addGap(18, 18, 18)
                                .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lNome)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lDataNascimento))
                            .addComponent(dcDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lEndereco)
                            .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTelefone)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lEmail))
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSalario)
                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGravarActionPerformed

        System.out.println("Clicou no botão gravar.");

        String nome = tfNome.getText();
        System.out.println(nome);

        if (nome.length() < 5) {
            System.out.println("Fazer alguma validação.");
        }

        Date dataNascimento = dcDataNascimento.getDate();
        System.out.println(dataNascimento);

        System.out.println(tfTelefone.getText());
        System.out.println(tfTelefone.getValue());

        System.out.println(tfSalario.getText());
        System.out.println(tfSalario.getValue());
//        System.out.println(tfSalario.getValue().getClass());

        Number salario = (Number) tfSalario.getValue();
        System.out.println(salario);

        Pessoa pessoa = new Pessoa(tfNome.getText(),
                dcDataNascimento.getDate(),
                tfEmail.getText(),
                tfEndereco.getText(),
                salario.doubleValue(),
                tfTelefone.getText());
        pessoaDao.adicionar(pessoa);

        exibir();

        controlarVisibilidadeBotoes(true);
        controlarVisibilidadeComponentes(false);


    }//GEN-LAST:event_bGravarActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed

//        controlarVisibilidadeBotoes(false);
//        controlarVisibilidadeComponentes(true);
        limparCampos();
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        controlarVisibilidadeBotoes(false);
        controlarVisibilidadeComponentes(true);

        try {
            Pessoa pessoa = pessoaDao.getPessoa(1);
            tfNome.setText(pessoa.getNome());
            tfEmail.setText(pessoa.getEmail());
            tfEndereco.setText(pessoa.getEndereco());
            tfTelefone.setText(pessoa.getTelefone());
            dcDataNascimento.setDate(pessoa.getDataNascimento());
            tfSalario.setValue(pessoa.getSalario());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR);
        }


    }//GEN-LAST:event_bAlterarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        try {
            pessoaDao.remover(1);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_bExcluirActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
//        controlarVisibilidadeBotoes(true);
//        controlarVisibilidadeComponentes(false);
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bGravar;
    private com.toedter.calendar.JDateChooser dcDataNascimento;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lDataNascimento;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSalario;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pComponentes;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfSalario;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables

    private void controlarVisibilidadeBotoes(boolean status) {
        bCadastrar.setEnabled(status);
        bAlterar.setEnabled(status);
        bExcluir.setEnabled(status);

        bGravar.setEnabled(!status);
        bCancelar.setEnabled(!status);
    }

    private void controlarVisibilidadeComponentes(boolean status) {
        Component componentes[] = pComponentes.getComponents();
        for (Component componente : componentes) {
            if (!(componente instanceof JLabel)) {
                componente.setEnabled(status);
            }
        }

    }

    private void exibir() {
        for (Pessoa p : pessoaDao.getTodos()) {
            System.out.println(p);
        }
    }

    private void limparCampos() {
        tfNome.setText("");
        tfEmail.setText("");
        tfEndereco.setText("");
        tfTelefone.setText("");
        tfSalario.setValue(0);
        dcDataNascimento.setDate(null);
    }

}
